version: '2'
services:
  luncher:
    build: .
    volumes:
      - .:/code
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
     POSTGRES_PASSWORD: getlunch
     POSTGRES_USER: luncher
